CREATE TABLE PEDIDOS (
    ID INT,
    DATAHORA TIMESTAMP,
    VENDEDORID INT, 
    CLIENTEID INT,
    TOTALDESCONTO DECIMAL(15,2) DEFAULT 0, 
    TOTALPEDIDO DECIMAL(12,2) DEFAULT 0,
    PRIMARY KEY (ID),
    FOREIGN KEY (VENDEDORID) REFERENCES VENDEDORES (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES (ID) ON DELETE CASCADE ON UPDATE CASCADE
);
