CREATE TABLE ITENS (
    ID INT,
    PEDIDOID INT,
    PRODUTOID INT,
    QUANTIDADE DECIMAL(15,2) DEFAULT 0,
    VALORUNITARIO DECIMAL(15,2) DEFAULT 0,
    VALORDESCONTO DECIMAL(15,2) DEFAULT 0,
    VALORTOTAL DECIMAL(15,2) COMPUTED BY (QUANTIDADE * VALORUNITARIO - VALORDESCONTO),
    PRIMARY KEY (ID),
    FOREIGN KEY (PEDIDOID) REFERENCES PEDIDOS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PRODUTOID) REFERENCES PRODUTOS (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

SET TERM ^;

CREATE  TRIGGER RECALC_PEDIDO FOR ITENS
ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 0
AS
BEGIN
    UPDATE PEDIDOS SET 
       TOTALDESCONTO = (SELECT SUM(VALORDESCONTO) FROM ITENS WHERE ITENS.PEDIDOID = PEDIDOS.ID),
       TOTALPEDIDO = (SELECT SUM(VALORTOTAL) FROM ITENS WHERE ITENS.PEDIDOID = PEDIDOS.ID)
    WHERE PEDIDOS.ID = NEW.PEDIDOID;
END^

SET TERM ;^
